package:
  name: alignqc
  version: "2.0.5"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/AlignQC.git

build:
  number: 0

requirements:
  build:
    - python 2.7.*
    - setuptools
  run:
    - python 2.7.*
    - r-essentials

about:
  home: https://github.com/jason-weirather/AlignQC
  license: Apache 2.0
  license_file: LICENSE
